<table class="table table-borderless table-responsive table-sm fw-bold" style="font-size: 12px">
    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">1</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">G</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>J</td>
            <td>T</td>
            <td>L</td>
            <td>U</td>
            <td>M</td>
            <td>A</td>
            <td>Z</td>
            <td>L</td>
            <td>A</td>
            <td>O</td>
            <td>E</td>
            <td>J</td>
            <td>O</td>
            <td>I</td>
            <td>E</td>
            <td>Z</td>
            <td>C</td>
            <td>W</td>
        </tr>
        <tr>
            <td>O</td>
            <td>B</td>
            <td>L</td>
            <td>M</td>
            <td>G</td>
            <td>Z</td>
            <td>Z</td>
            <td>Z</td>
            <td>A</td>
            <td>Q</td>
            <td>L</td>
            <td>L</td>
            <td>A</td>
            <td>Q</td>
            <td>S</td>
            <td>H</td>
            <td>M</td>
            <td>J</td>
        </tr>
        <tr>
            <td>X</td>
            <td>A</td>
            <td>G</td>
            <td>T</td>
            <td>V</td>
            <td>X</td>
            <td>V</td>
            <td>P</td>
            <td>I</td>
            <td>Q</td>
            <td>T</td>
            <td>R</td>
            <td>F</td>
            <td>M</td>
            <td>C</td>
            <td>U</td>
            <td>V</td>
            <td>J</td>
        </tr>
        <tr>
            <td>X</td>
            <td>U</td>
            <td>M</td>
            <td>R</td>
            <td>F</td>
            <td>H</td>
            <td>Z</td>
            <td>W</td>
            <td>K</td>
            <td>E</td>
            <td>S</td>
            <td>T</td>
            <td>O</td>
            <td>L</td>
            <td>S</td>
            <td>S</td>
            <td>Y</td>
            <td>Q</td>
        </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">2</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">G</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>N</td>
            <td>P</td>
            <td>R</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>N</td>
            <td>G</td>
            <td>A</td>
            <td>F</td>
            <td>K</td>
            <td>K</td>
            <td>R</td>
            <td>B</td>
        </tr>
        <tr>
            <td>N</td>
            <td>G</td>
            <td>J</td>
            <td>H</td>
            <td>G</td>
            <td>H</td>
            <td>Y</td>
            <td>K</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>F</td>
            <td>G</td>
            <td>A</td>
            <td>J</td>
            <td>G</td>
            <td>L</td>
        </tr>
        <tr>
            <td>D</td>
            <td>N</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>U</td>
            <td>G</td>
            <td>U</td>
            <td>D</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>J</td>
        </tr>
        <tr>
            <td>G</td>
            <td>G</td>
            <td>G</td>
            <td>B</td>
            <td>V</td>
            <td>O</td>
            <td>D</td>
            <td>X</td>
            <td>C</td>
            <td>T</td>
            <td>E</td>
            <td>K</td>
            <td>F</td>
            <td>S</td>
            <td>O</td>
            <td>T</td>
            <td>G</td>
            <td>Q</td>
        </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">3</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">I</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>I</td>
            <td>I</td>
            <td>S</td>
            <td>V</td>
            <td>X</td>
            <td>F</td>
            <td>L</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>M</td>
            <td>G</td>
            <td>R</td>
            <td>W</td>
            <td>J</td>
        </tr>
        <tr>
            <td>W</td>
            <td>I</td>
            <td>I</td>
            <td>Q</td>
            <td>Z</td>
            <td>E</td>
            <td>S</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>B</td>
            <td>Q</td>
            <td>Q</td>
            <td>S</td>
            <td>M</td>
            <td>I</td>
            <td>O</td>
        </tr>
        <tr>
            <td>I</td>
            <td>Z</td>
            <td>I</td>
            <td>I</td>
            <td>A</td>
            <td>I</td>
            <td>Y</td>
            <td>F</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
            <td>L</td>
            <td>I</td>
            <td>V</td>
            <td>M</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
        </tr>
        <tr>
            <td>K</td>
            <td>I</td>
            <td>I</td>
            <td>V</td>
            <td>G</td>
            <td>K</td>
            <td>U</td>
            <td>A</td>
            <td>Z</td>
            <td>I</td>
            <td>I</td>
            <td>G</td>
            <td>E</td>
            <td>I</td>
            <td>M</td>
            <td>I</td>
            <td>I</td>
            <td>I</td>
        </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">4</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">T</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>D</td>
            <td>B</td>
            <td>O</td>
            <td>C</td>
            <td>T</td>
            <td>I</td>
            <td>R</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
            <td>F</td>
        </tr>
        <tr>
            <td>G</td>
            <td>T</td>
            <td>W</td>
            <td>T</td>
            <td>R</td>
            <td>S</td>
            <td>J</td>
            <td>T</td>
            <td>W</td>
            <td>A</td>
            <td>G</td>
            <td>Y</td>
            <td>Q</td>
            <td>H</td>
            <td>P</td>
            <td>D</td>
            <td>T</td>
            <td>P</td>
        </tr>
        <tr>
            <td>A</td>
            <td>O</td>
            <td>G</td>
            <td>R</td>
            <td>M</td>
            <td>H</td>
            <td>J</td>
            <td>Z</td>
            <td>N</td>
            <td>S</td>
            <td>S</td>
            <td>Z</td>
            <td>S</td>
            <td>T</td>
            <td>L</td>
            <td>H</td>
            <td>A</td>
            <td>S</td>
        </tr>
        <tr>
            <td>I</td>
            <td>K</td>
            <td>A</td>
            <td>U</td>
            <td>D</td>
            <td>S</td>
            <td>F</td>
            <td>T</td>
            <td>K</td>
            <td>H</td>
            <td>Z</td>
            <td>A</td>
            <td>I</td>
            <td>I</td>
            <td>S</td>
            <td>T</td>
            <td>I</td>
            <td>B</td>
        </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">5</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">S</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>U</td>
            <td>Q</td>
            <td>R</td>
            <td>G</td>
            <td>X</td>
            <td>E</td>
            <td>D</td>
            <td>J</td>
            <td>Z</td>
            <td>T</td>
            <td>A</td>
            <td>A</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>D</td>
            <td>Z</td>
            <td>R</td>
        </tr>
        <tr>
            <td>H</td>
            <td>B</td>
            <td>L</td>
            <td>V</td>
            <td>T</td>
            <td>S</td>
            <td>J</td>
            <td>S</td>
            <td>W</td>
            <td>D</td>
            <td>P</td>
            <td>Q</td>
            <td>N</td>
            <td>B</td>
            <td>R</td>
            <td>Y</td>
            <td>S</td>
            <td>X</td>
        </tr>
        <tr>
            <td>R</td>
            <td>R</td>
            <td>I</td>
            <td>C</td>
            <td>R</td>
            <td>S</td>
            <td>B</td>
            <td>A</td>
            <td>L</td>
            <td>S</td>
            <td>X</td>
            <td>C</td>
            <td>T</td>
            <td>N</td>
            <td>X</td>
            <td>A</td>
            <td>N</td>
            <td>W</td>
        </tr>
        <tr>
            <td>S</td>
            <td>E</td>
            <td>G</td>
            <td>N</td>
            <td>L</td>
            <td>W</td>
            <td>I</td>
            <td>Y</td>
            <td>S</td>
            <td>V</td>
            <td>S</td>
            <td>O</td>
            <td>C</td>
            <td>S</td>
            <td>W</td>
            <td>N</td>
            <td>Q</td>
            <td>I</td>
        </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">6</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">B</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
            <td>J</td>
            <td>B</td>
            <td>H</td>
            <td>R</td>
            <td>M</td>
            <td>Z</td>
            <td>R</td>
            <td>S</td>
            <td>H</td>
            <td>Q</td>
            <td>K</td>
            <td>M</td>
            <td>B</td>
            <td>Q</td>
            <td>B</td>
            <td>U</td>
            <td>H</td>
            <td>R</td>
        </tr>
        <tr>
            <td>H</td>
            <td>J</td>
            <td>V</td>
            <td>T</td>
            <td>Y</td>
            <td>B</td>
            <td>A</td>
            <td>L</td>
            <td>B</td>
            <td>W</td>
            <td>V</td>
            <td>F</td>
            <td>N</td>
            <td>Q</td>
            <td>I</td>
            <td>R</td>
            <td>I</td>
            <td>S</td>
        </tr>
        <tr>
            <td>Y</td>
            <td>L</td>
            <td>E</td>
            <td>B</td>
            <td>O</td>
            <td>W</td>
            <td>R</td>
            <td>J</td>
            <td>C</td>
            <td>C</td>
            <td>B</td>
            <td>F</td>
            <td>G</td>
            <td>T</td>
            <td>N</td>
            <td>J</td>
            <td>R</td>
            <td>P</td>
        </tr>
        <tr>
            <td>O</td>
            <td>H</td>
            <td>R</td>
            <td>O</td>
            <td>M</td>
            <td>S</td>
            <td>R</td>
            <td>T</td>
            <td>Y</td>
            <td>E</td>
            <td>U</td>
            <td>W</td>
            <td>Y</td>
            <td>P</td>
            <td>Y</td>
            <td>Z</td>
            <td>R</td>
            <td>M</td>
        </tr>
    </tbody>
</table>
