<table class="table table-borderless table-responsive table-sm fw-bold" style="font-size: 12px">
    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">1</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">E</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>N</td>
        <td>R</td>
        <td>A</td>
        <td>I</td>
        <td>V</td>
        <td>M</td>
        <td>B</td>
        <td>H</td>
        <td>A</td>
        <td>I</td>
        <td>E</td>
        <td>F</td>
        <td>D</td>
        <td>C</td>
        <td>C</td>
        <td>D</td>
        <td>D</td>
        <td>U</td>
    </tr>
    <tr>
        <td>L</td>
        <td>P</td>
        <td>R</td>
        <td>Y</td>
        <td>R</td>
        <td>Z</td>
        <td>A</td>
        <td>A</td>
        <td>C</td>
        <td>C</td>
        <td>M</td>
        <td>D</td>
        <td>O</td>
        <td>Q</td>
        <td>F</td>
        <td>K</td>
        <td>W</td>
        <td>C</td>
    </tr>
    <tr>
        <td>O</td>
        <td>N</td>
        <td>K</td>
        <td>B</td>
        <td>J</td>
        <td>F</td>
        <td>G</td>
        <td>H</td>
        <td>G</td>
        <td>E</td>
        <td>Q</td>
        <td>K</td>
        <td>I</td>
        <td>F</td>
        <td>G</td>
        <td>V</td>
        <td>S</td>
        <td>I</td>
    </tr>
    <tr>
        <td>H</td>
        <td>D</td>
        <td>B</td>
        <td>F</td>
        <td>G</td>
        <td>E</td>
        <td>Z</td>
        <td>J</td>
        <td>U</td>
        <td>B</td>
        <td>X</td>
        <td>Y</td>
        <td>Z</td>
        <td>D</td>
        <td>V</td>
        <td>J</td>
        <td>T</td>
        <td>G</td>
    </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">2</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">V</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>T</td>
        <td>W</td>
        <td>G</td>
        <td>A</td>
        <td>G</td>
        <td>O</td>
        <td>I</td>
        <td>L</td>
        <td>J</td>
        <td>L</td>
        <td>P</td>
        <td>O</td>
        <td>V</td>
        <td>T</td>
        <td>H</td>
        <td>F</td>
        <td>S</td>
        <td>X</td>
    </tr>
    <tr>
        <td>N</td>
        <td>H</td>
        <td>I</td>
        <td>E</td>
        <td>A</td>
        <td>V</td>
        <td>E</td>
        <td>D</td>
        <td>M</td>
        <td>V</td>
        <td>V</td>
        <td>J</td>
        <td>V</td>
        <td>J</td>
        <td>N</td>
        <td>F</td>
        <td>M</td>
        <td>H</td>
    </tr>
    <tr>
        <td>R</td>
        <td>S</td>
        <td>R</td>
        <td>K</td>
        <td>F</td>
        <td>I</td>
        <td>W</td>
        <td>I</td>
        <td>P</td>
        <td>V</td>
        <td>A</td>
        <td>W</td>
        <td>V</td>
        <td>V</td>
        <td>T</td>
        <td>D</td>
        <td>P</td>
        <td>S</td>
    </tr>
    <tr>
        <td>S</td>
        <td>F</td>
        <td>D</td>
        <td>V</td>
        <td>E</td>
        <td>N</td>
        <td>L</td>
        <td>V</td>
        <td>V</td>
        <td>V</td>
        <td>R</td>
        <td>N</td>
        <td>L</td>
        <td>X</td>
        <td>D</td>
        <td>H</td>
        <td>T</td>
        <td>R</td>
    </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">3</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">G</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>W</td>
        <td>Q</td>
        <td>T</td>
        <td>G</td>
        <td>W</td>
        <td>R</td>
        <td>R</td>
        <td>G</td>
        <td>Y</td>
        <td>P</td>
        <td>R</td>
        <td>B</td>
        <td>G</td>
        <td>P</td>
        <td>V</td>
        <td>V</td>
        <td>I</td>
        <td>W</td>
    </tr>
    <tr>
        <td>O</td>
        <td>R</td>
        <td>U</td>
        <td>Y</td>
        <td>G</td>
        <td>E</td>
        <td>O</td>
        <td>N</td>
        <td>I</td>
        <td>O</td>
        <td>N</td>
        <td>W</td>
        <td>D</td>
        <td>H</td>
        <td>R</td>
        <td>D</td>
        <td>R</td>
        <td>F</td>
    </tr>
    <tr>
        <td>B</td>
        <td>X</td>
        <td>J</td>
        <td>G</td>
        <td>R</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>Y</td>
        <td>P</td>
        <td>S</td>
        <td>D</td>
    </tr>
    <tr>
        <td>M</td>
        <td>R</td>
        <td>R</td>
        <td>S</td>
        <td>J</td>
        <td>B</td>
        <td>A</td>
        <td>C</td>
        <td>J</td>
        <td>Y</td>
        <td>D</td>
        <td>M</td>
        <td>D</td>
        <td>Z</td>
        <td>C</td>
        <td>Z</td>
        <td>G</td>
        <td>K</td>
    </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">4</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">U</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
    </tr>
    <tr>
        <td>F</td>
        <td>V</td>
        <td>S</td>
        <td>K</td>
        <td>Z</td>
        <td>V</td>
        <td>X</td>
        <td>G</td>
        <td>V</td>
        <td>C</td>
        <td>S</td>
        <td>S</td>
        <td>K</td>
        <td>Z</td>
        <td>V</td>
        <td>G</td>
        <td>L</td>
        <td>B</td>
    </tr>
    <tr>
        <td>B</td>
        <td>N</td>
        <td>V</td>
        <td>U</td>
        <td>V</td>
        <td>G</td>
        <td>V</td>
        <td>S</td>
        <td>K</td>
        <td>Z</td>
        <td>V</td>
        <td>V</td>
        <td>S</td>
        <td>V</td>
        <td>G</td>
        <td>Y</td>
        <td>S</td>
        <td>G</td>
    </tr>
    <tr>
        <td>N</td>
        <td>X</td>
        <td>N</td>
        <td>R</td>
        <td>S</td>
        <td>H</td>
        <td>N</td>
        <td>V</td>
        <td>S</td>
        <td>V</td>
        <td>G</td>
        <td>G</td>
        <td>A</td>
        <td>X</td>
        <td>Q</td>
        <td>R</td>
        <td>T</td>
        <td>K</td>
    </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">5</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">V</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>Q</td>
        <td>R</td>
        <td>S</td>
        <td>T</td>
        <td>I</td>
        <td>S</td>
        <td>T</td>
        <td>I</td>
        <td>S</td>
        <td>A</td>
        <td>H</td>
        <td>A</td>
        <td>R</td>
        <td>S</td>
        <td>T</td>
        <td>I</td>
        <td>V</td>
        <td>Q</td>
    </tr>
    <tr>
        <td>O</td>
        <td>U</td>
        <td>M</td>
        <td>K</td>
        <td>K</td>
        <td>M</td>
        <td>K</td>
        <td>K</td>
        <td>V</td>
        <td>S</td>
        <td>N</td>
        <td>Z</td>
        <td>U</td>
        <td>M</td>
        <td>K</td>
        <td>K</td>
        <td>L</td>
        <td>L</td>
    </tr>
    <tr>
        <td>U</td>
        <td>K</td>
        <td>K</td>
        <td>S</td>
        <td>W</td>
        <td>K</td>
        <td>S</td>
        <td>W</td>
        <td>G</td>
        <td>S</td>
        <td>T</td>
        <td>Q</td>
        <td>K</td>
        <td>K</td>
        <td>S</td>
        <td>W</td>
        <td>S</td>
        <td>T</td>
    </tr>
    <tr>
        <td>H</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>F</td>
        <td>F</td>
        <td>G</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>L</td>
        <td>G</td>
    </tr>
    </tbody>

    <thead>
        <tr class="text-black">
            <th colspan="16" scope="col">6</th>

            <th style="border: 1px solid black ;text-align: center;" scope="col">K</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="borderBt">
        <tr>
        <td>F</td>
        <td>Q</td>
        <td>B</td>
        <td>L</td>
        <td>R</td>
        <td>T</td>
        <td>I</td>
        <td>V</td>
        <td>K</td>
        <td>T</td>
        <td>Q</td>
        <td>B</td>
        <td>L</td>
        <td>R</td>
        <td>K</td>
        <td>K</td>
        <td>D</td>
        <td>K</td>
    </tr>
    <tr>
        <td>V</td>
        <td>D</td>
        <td>T</td>
        <td>T</td>
        <td>Z</td>
        <td>K</td>
        <td>K</td>
        <td>D</td>
        <td>S</td>
        <td>F</td>
        <td>D</td>
        <td>T</td>
        <td>T</td>
        <td>Z</td>
        <td>C</td>
        <td>K</td>
        <td>P</td>
        <td>A</td>
    </tr>
    <tr>
        <td>H</td>
        <td>A</td>
        <td>B</td>
        <td>S</td>
        <td>H</td>
        <td>S</td>
        <td>W</td>
        <td>R</td>
        <td>K</td>
        <td>G</td>
        <td>A</td>
        <td>B</td>
        <td>S</td>
        <td>H</td>
        <td>K</td>
        <td>K</td>
        <td>Z</td>
        <td>K</td>
    </tr>
    <tr>
        <td>K</td>
        <td>X</td>
        <td>J</td>
        <td>E</td>
        <td>Z</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>K</td>
        <td>M</td>
        <td>X</td>
        <td>J</td>
        <td>E</td>
        <td>Z</td>
        <td>S</td>
        <td>K</td>
        <td>U</td>
        <td>W</td>
    </tr>
    </tbody>
</table>
