<table class="table table-borderless table-responsive table-sm fw-bold " style="font-size: 12px">
    <thead>
    <tr class="text-black table-sm fs-6">
        <th colspan="16" scope="col">1</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">C</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>Q</td>
        <td>S</td>
        <td>V</td>
        <td>R</td>
        <td>E</td>
        <td>X</td>
        <td>P</td>
        <td>R</td>
        <td>R</td>
        <td>T</td>
        <td>L</td>
        <td>F</td>
        <td>Z</td>
        <td>V</td>
        <td>D</td>
        <td>Q</td>
        <td>T</td>
        <td>O</td>
    </tr>
    <tr>
        <td>V</td>
        <td>H</td>
        <td>W</td>
        <td>D</td>
        <td>F</td>
        <td>G</td>
        <td>P</td>
        <td>J</td>
        <td>R</td>
        <td>D</td>
        <td>N</td>
        <td>C</td>
        <td>Y</td>
        <td>U</td>
        <td>T</td>
        <td>R</td>
        <td>X</td>
        <td>L</td>
    </tr>
    <tr>
        <td>T</td>
        <td>M</td>
        <td>A</td>
        <td>T</td>
        <td>E</td>
        <td>K</td>
        <td>B</td>
        <td>Q</td>
        <td>G</td>
        <td>V</td>
        <td>Y</td>
        <td>E</td>
        <td>Y</td>
        <td>U</td>
        <td>I</td>
        <td>S</td>
        <td>G</td>
        <td>F</td>
    </tr>
    <tr>
        <td>C</td>
        <td>I</td>
        <td>G</td>
        <td>N</td>
        <td>X</td>
        <td>V</td>
        <td>K</td>
        <td>H</td>
        <td>B</td>
        <td>S</td>
        <td>H</td>
        <td>X</td>
        <td>X</td>
        <td>A</td>
        <td>U</td>
        <td>J</td>
        <td>I</td>
        <td>O</td>
    </tr>
    </tbody>

    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">2</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">F</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>F</td>
        <td>S</td>
        <td>E</td>
        <td>Y</td>
        <td>M</td>
        <td>N</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>X</td>
        <td>S</td>
        <td>E</td>
        <td>T</td>
    </tr>
    <tr>
        <td>F</td>
        <td>U</td>
        <td>Q</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>S</td>
        <td>V</td>
        <td>Z</td>
        <td>Y</td>
        <td>S</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>S</td>
        <td>P</td>
        <td>U</td>
        <td>Z</td>
    </tr>
    <tr>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>S</td>
        <td>R</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>E</td>
    </tr>
    <tr>
        <td>A</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>C</td>
        <td>Q</td>
        <td>R</td>
        <td>A</td>
        <td>U</td>
        <td>N</td>
        <td>Z</td>
        <td>Q</td>
        <td>V</td>
        <td>F</td>
        <td>F</td>
        <td>F</td>
        <td>R</td>
    </tr>
    </tbody>

    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">3</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">G</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>X</td>
        <td>N</td>
        <td>Z</td>
        <td>U</td>
        <td>B</td>
        <td>K</td>
        <td>D</td>
        <td>H</td>
        <td>R</td>
        <td>G</td>
        <td>G</td>
        <td>T</td>
        <td>G</td>
        <td>U</td>
        <td>R</td>
        <td>V</td>
        <td>K</td>
        <td>G</td>
    </tr>
    <tr>
        <td>M</td>
        <td>G</td>
        <td>D</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>L</td>
        <td>I</td>
        <td>K</td>
        <td>G</td>
    </tr>
    <tr>
        <td>G</td>
        <td>G</td>
        <td>V</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>W</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>S</td>
        <td>M</td>
        <td>G</td>
    </tr>
    <tr>
        <td>G</td>
        <td>O</td>
        <td>R</td>
        <td>Q</td>
        <td>I</td>
        <td>T</td>
        <td>J</td>
        <td>W</td>
        <td>D</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>G</td>
        <td>J</td>
        <td>G</td>
        <td>G</td>
    </tr>
    </tbody>

    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">4</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">C</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>W</td>
        <td>S</td>
        <td>C</td>
        <td>U</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
        <td>R</td>
    </tr>
    <tr>
        <td>W</td>
        <td>M</td>
        <td>Y</td>
        <td>S</td>
        <td>C</td>
        <td>E</td>
        <td>S</td>
        <td>A</td>
        <td>R</td>
        <td>S</td>
        <td>Z</td>
        <td>U</td>
        <td>H</td>
        <td>D</td>
        <td>Q</td>
        <td>Q</td>
        <td>A</td>
        <td>O</td>
    </tr>
    <tr>
        <td>H</td>
        <td>E</td>
        <td>J</td>
        <td>C</td>
        <td>G</td>
        <td>J</td>
        <td>X</td>
        <td>V</td>
        <td>K</td>
        <td>G</td>
        <td>F</td>
        <td>F</td>
        <td>S</td>
        <td>B</td>
        <td>F</td>
        <td>V</td>
        <td>F</td>
        <td>Y</td>
    </tr>
    <tr>
        <td>R</td>
        <td>A</td>
        <td>R</td>
        <td>R</td>
        <td>L</td>
        <td>C</td>
        <td>T</td>
        <td>Z</td>
        <td>Q</td>
        <td>E</td>
        <td>X</td>
        <td>D</td>
        <td>N</td>
        <td>M</td>
        <td>L</td>
        <td>X</td>
        <td>C</td>
        <td>G</td>
    </tr>
    </tbody>

    <thead>
    <tr class="text-black">
        <th scope="col" colspan="16">5</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">Q</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>O</td>
        <td>H</td>
        <td>D</td>
        <td>K</td>
        <td>I</td>
        <td>M</td>
        <td>U</td>
        <td>B</td>
        <td>Q</td>
        <td>Q</td>
        <td>Q</td>
        <td>N</td>
        <td>F</td>
        <td>L</td>
        <td>Z</td>
        <td>I</td>
        <td>T</td>
        <td>Q</td>
    </tr>
    <tr>
        <td>R</td>
        <td>L</td>
        <td>R</td>
        <td>C</td>
        <td>U</td>
        <td>Q</td>
        <td>T</td>
        <td>G</td>
        <td>X</td>
        <td>Q</td>
        <td>T</td>
        <td>R</td>
        <td>E</td>
        <td>G</td>
        <td>X</td>
        <td>M</td>
        <td>X</td>
        <td>M</td>
    </tr>
    <tr>
        <td>U</td>
        <td>Y</td>
        <td>U</td>
        <td>O</td>
        <td>S</td>
        <td>C</td>
        <td>B</td>
        <td>H</td>
        <td>P</td>
        <td>I</td>
        <td>Y</td>
        <td>E</td>
        <td>M</td>
        <td>B</td>
        <td>F</td>
        <td>J</td>
        <td>C</td>
        <td>L</td>
    </tr>
    <tr>
        <td>K</td>
        <td>X</td>
        <td>U</td>
        <td>X</td>
        <td>D</td>
        <td>S</td>
        <td>X</td>
        <td>V</td>
        <td>B</td>
        <td>T</td>
        <td>E</td>
        <td>K</td>
        <td>U</td>
        <td>J</td>
        <td>R</td>
        <td>P</td>
        <td>D</td>
        <td>E</td>
    </tr>
    </tbody>

    <thead>
    <tr class="text-black">
        <th scope="col" colspan="16">6</th>

        <th style="border: 1px solid black ;text-align: center;" scope="col">Z</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody style="border-bottom: 1px solid black">
    <tr>
        <td>M</td>
        <td>A</td>
        <td>D</td>
        <td>J</td>
        <td>U</td>
        <td>R</td>
        <td>S</td>
        <td>Z</td>
        <td>Q</td>
        <td>H</td>
        <td>R</td>
        <td>T</td>
        <td>X</td>
        <td>Q</td>
        <td>T</td>
        <td>R</td>
        <td>J</td>
        <td>O</td>
    </tr>
    <tr>
        <td>T</td>
        <td>Z</td>
        <td>M</td>
        <td>N</td>
        <td>A</td>
        <td>X</td>
        <td>Q</td>
        <td>T</td>
        <td>R</td>
        <td>Z</td>
        <td>V</td>
        <td>O</td>
        <td>P</td>
        <td>I</td>
        <td>Y</td>
        <td>E</td>
        <td>R</td>
        <td>X</td>
    </tr>
    <tr>
        <td>Q</td>
        <td>K</td>
        <td>P</td>
        <td>X</td>
        <td>I</td>
        <td>P</td>
        <td>I</td>
        <td>Y</td>
        <td>E</td>
        <td>Y</td>
        <td>B</td>
        <td>B</td>
        <td>A</td>
        <td>F</td>
        <td>Q</td>
        <td>F</td>
        <td>Y</td>
        <td>B</td>
    </tr>
    <tr>
        <td>Q</td>
        <td>M</td>
        <td>A</td>
        <td>T</td>
        <td>Q</td>
        <td>S</td>
        <td>W</td>
        <td>F</td>
        <td>H</td>
        <td>T</td>
        <td>X</td>
        <td>Z</td>
        <td>Q</td>
        <td>R</td>
        <td>W</td>
        <td>J</td>
        <td>O</td>
        <td>C</td>
    </tr>
    </tbody>

</table>
