<table
    class="table table-borderless table-responsive table-sm fw-bold"
    style="font-size: 12px"
>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">1</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">V</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>Q</td>
        <td>A</td>
        <td>Q</td>
        <td>W</td>
        <td>O</td>
        <td>W</td>
        <td>G</td>
        <td>R</td>
        <td>J</td>
        <td>B</td>
        <td>N</td>
        <td>Q</td>
        <td>N</td>
        <td>K</td>
        <td>G</td>
        <td>X</td>
        <td>X</td>
        <td>K</td>
    </tr>
    <tr>
        <td>X</td>
        <td>K</td>
        <td>O</td>
        <td>V</td>
        <td>R</td>
        <td>T</td>
        <td>A</td>
        <td>A</td>
        <td>L</td>
        <td>Q</td>
        <td>S</td>
        <td>K</td>
        <td>Y</td>
        <td>Y</td>
        <td>O</td>
        <td>F</td>
        <td>C</td>
        <td>M</td>
    </tr>
    <tr>
        <td>K</td>
        <td>V</td>
        <td>C</td>
        <td>M</td>
        <td>O</td>
        <td>N</td>
        <td>T</td>
        <td>Q</td>
        <td>I</td>
        <td>H</td>
        <td>P</td>
        <td>R</td>
        <td>A</td>
        <td>Z</td>
        <td>Q</td>
        <td>M</td>
        <td>M</td>
        <td>X</td>
    </tr>
    <tr>
        <td>J</td>
        <td>G</td>
        <td>T</td>
        <td>O</td>
        <td>N</td>
        <td>H</td>
        <td>T</td>
        <td>K</td>
        <td>M</td>
        <td>Q</td>
        <td>N</td>
        <td>Z</td>
        <td>E</td>
        <td>J</td>
        <td>N</td>
        <td>Q</td>
        <td>F</td>
        <td>O</td>
    </tr>
    </tbody>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">2</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">C</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>E</td>
        <td>P</td>
        <td>B</td>
        <td>Z</td>
        <td>C</td>
        <td>S</td>
        <td>C</td>
        <td>B</td>
        <td>Q</td>
        <td>P</td>
        <td>Y</td>
        <td>B</td>
        <td>J</td>
        <td>U</td>
        <td>I</td>
        <td>F</td>
        <td>A</td>
        <td>N</td>
    </tr>
    <tr>
        <td>P</td>
        <td>U</td>
        <td>C</td>
        <td>L</td>
        <td>I</td>
        <td>C</td>
        <td>O</td>
        <td>W</td>
        <td>A</td>
        <td>C</td>
        <td>R</td>
        <td>C</td>
        <td>C</td>
        <td>J</td>
        <td>A</td>
        <td>Y</td>
        <td>M</td>
        <td>U</td>
    </tr>
    <tr>
        <td>Y</td>
        <td>X</td>
        <td>J</td>
        <td>U</td>
        <td>F</td>
        <td>D</td>
        <td>T</td>
        <td>R</td>
        <td>U</td>
        <td>T</td>
        <td>Q</td>
        <td>I</td>
        <td>S</td>
        <td>F</td>
        <td>V</td>
        <td>O</td>
        <td>D</td>
        <td>X</td>
    </tr>
    <tr>
        <td>P</td>
        <td>D</td>
        <td>Y</td>
        <td>P</td>
        <td>N</td>
        <td>F</td>
        <td>D</td>
        <td>Z</td>
        <td>X</td>
        <td>T</td>
        <td>K</td>
        <td>M</td>
        <td>H</td>
        <td>X</td>
        <td>A</td>
        <td>C</td>
        <td>H</td>
        <td>D</td>
    </tr>
    </tbody>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">3</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">N</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>R</td>
        <td>W</td>
        <td>S</td>
        <td>F</td>
        <td>E</td>
        <td>K</td>
        <td>S</td>
        <td>B</td>
        <td>C</td>
        <td>U</td>
        <td>M</td>
        <td>D</td>
        <td>N</td>
        <td>Y</td>
        <td>Y</td>
        <td>D</td>
        <td>O</td>
        <td>R</td>
    </tr>
    <tr>
        <td>O</td>
        <td>A</td>
        <td>N</td>
        <td>L</td>
        <td>N</td>
        <td>S</td>
        <td>E</td>
        <td>G</td>
        <td>N</td>
        <td>N</td>
        <td>W</td>
        <td>E</td>
        <td>E</td>
        <td>Q</td>
        <td>W</td>
        <td>A</td>
        <td>H</td>
        <td>D</td>
    </tr>
    <tr>
        <td>W</td>
        <td>S</td>
        <td>E</td>
        <td>N</td>
        <td>H</td>
        <td>K</td>
        <td>N</td>
        <td>A</td>
        <td>Z</td>
        <td>O</td>
        <td>R</td>
        <td>J</td>
        <td>I</td>
        <td>J</td>
        <td>W</td>
        <td>P</td>
        <td>N</td>
        <td>W</td>
    </tr>
    <tr>
        <td>G</td>
        <td>N</td>
        <td>S</td>
        <td>T</td>
        <td>Y</td>
        <td>Y</td>
        <td>Q</td>
        <td>K</td>
        <td>K</td>
        <td>G</td>
        <td>O</td>
        <td>N</td>
        <td>G</td>
        <td>M</td>
        <td>R</td>
        <td>U</td>
        <td>G</td>
        <td>S</td>
    </tr>
    </tbody>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">4</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">J</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>O</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
        <td>P</td>
    </tr>
    <tr>
        <td>H</td>
        <td>Q</td>
        <td>J</td>
        <td>A</td>
        <td>L</td>
        <td>R</td>
        <td>S</td>
        <td>V</td>
        <td>T</td>
        <td>Q</td>
        <td>I</td>
        <td>R</td>
        <td>G</td>
        <td>V</td>
        <td>I</td>
        <td>W</td>
        <td>M</td>
        <td>E</td>
    </tr>
    <tr>
        <td>C</td>
        <td>V</td>
        <td>T</td>
        <td>Q</td>
        <td>I</td>
        <td>R</td>
        <td>R</td>
        <td>A</td>
        <td>V</td>
        <td>U</td>
        <td>C</td>
        <td>I</td>
        <td>E</td>
        <td>O</td>
        <td>M</td>
        <td>K</td>
        <td>T</td>
        <td>D</td>
    </tr>
    <tr>
        <td>N</td>
        <td>J</td>
        <td>T</td>
        <td>K</td>
        <td>M</td>
        <td>F</td>
        <td>Y</td>
        <td>W</td>
        <td>X</td>
        <td>D</td>
        <td>N</td>
        <td>V</td>
        <td>F</td>
        <td>S</td>
        <td>H</td>
        <td>X</td>
        <td>A</td>
        <td>Q</td>
    </tr>
    </tbody>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">5</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">Z</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>M</td>
        <td>X</td>
        <td>P</td>
        <td>A</td>
        <td>Z</td>
        <td>J</td>
        <td>H</td>
        <td>L</td>
        <td>L</td>
        <td>S</td>
        <td>W</td>
        <td>E</td>
        <td>J</td>
        <td>H</td>
        <td>L</td>
        <td>L</td>
        <td>S</td>
        <td>W</td>
    </tr>
    <tr>
        <td>T</td>
        <td>S</td>
        <td>S</td>
        <td>Q</td>
        <td>O</td>
        <td>R</td>
        <td>G</td>
        <td>W</td>
        <td>M</td>
        <td>B</td>
        <td>N</td>
        <td>O</td>
        <td>R</td>
        <td>G</td>
        <td>W</td>
        <td>M</td>
        <td>B</td>
        <td>N</td>
    </tr>
    <tr>
        <td>T</td>
        <td>R</td>
        <td>I</td>
        <td>C</td>
        <td>K</td>
        <td>T</td>
        <td>N</td>
        <td>S</td>
        <td>G</td>
        <td>D</td>
        <td>Y</td>
        <td>K</td>
        <td>T</td>
        <td>N</td>
        <td>S</td>
        <td>G</td>
        <td>D</td>
        <td>Y</td>
    </tr>
    <tr>
        <td>U</td>
        <td>S</td>
        <td>C</td>
        <td>H</td>
        <td>X</td>
        <td>R</td>
        <td>N</td>
        <td>S</td>
        <td>Z</td>
        <td>J</td>
        <td>S</td>
        <td>M</td>
        <td>Z</td>
        <td>G</td>
        <td>U</td>
        <td>Y</td>
        <td>F</td>
        <td>R</td>
    </tr>
    </tbody>
    <thead>
    <tr class="text-black">
        <th colspan="16" scope="col">6</th>
        <th style="border: 1px solid black ;text-align: center;" scope="col">Y</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="borderBt">
    <tr>
        <td>S</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>K</td>
        <td>T</td>
        <td>P</td>
        <td>O</td>
        <td>S</td>
        <td>S</td>
        <td>K</td>
        <td>T</td>
        <td>P</td>
        <td>O</td>
        <td>S</td>
        <td>S</td>
        <td>U</td>
        <td>F</td>
    </tr>
    <tr>
        <td>Y</td>
        <td>Y</td>
        <td>T</td>
        <td>Y</td>
        <td>F</td>
        <td>Z</td>
        <td>F</td>
        <td>K</td>
        <td>D</td>
        <td>A</td>
        <td>F</td>
        <td>Z</td>
        <td>F</td>
        <td>K</td>
        <td>D</td>
        <td>A</td>
        <td>K</td>
        <td>Y</td>
    </tr>
    <tr>
        <td>U</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>C</td>
        <td>T</td>
        <td>V</td>
        <td>F</td>
        <td>T</td>
        <td>C</td>
        <td>C</td>
        <td>T</td>
        <td>V</td>
        <td>F</td>
        <td>T</td>
        <td>C</td>
        <td>Y</td>
        <td>Q</td>
    </tr>
    <tr>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>S</td>
        <td>Y</td>
        <td>N</td>
        <td>T</td>
        <td>K</td>
        <td>M</td>
        <td>D</td>
        <td>R</td>
        <td>M</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>H</td>
        <td>G</td>
    </tr>
    </tbody>
</table>
